main: se.le00nn.randomtp.RandomSpawn
version: 1.3.0
name: RandomSpawn
author: Le00nn
description: Spawns a player in a random area in a range set in a config file.
commands:
    rs:
        description: Used for configuring and reloading the config.yml file.
