main: se.le00nn.randomtp.RandomTP
version: 1.1.0
name: RandomSpawn
author: Le00nn
description: Spawns a player in a random area in a range set a config file.
commands:
    rs:
        description: Used for reloading config.yml file.
